@startuml
skinparam{
  defaultFontName GenShinGothic-P CJK JP Regular
}
left to right direction

:作業者:
:管理者:

rectangle "作業者の管理ができるようになる" {
    package 作業者管理 {
        作業者--->(作業者の新規登録をする)
        作業者--->(作業者のプロフィールを見る)
        作業者--->(作業者のスケジュールを見る)
        作業者--->(作業者のプロフィールを変更)
        作業者--->(作業者のスケジュールを変更)
        作業者--->(作業者の削除をする)
        (作業者のプロフィールを見る)<---管理者
        (作業者のスケジュールを見る)<---管理者
        (作業者の削除をする)<---管理者
    }
}
@enduml
